require:
  - rubocop-rails

AllCops:
  NewCops: enable

# disable "Missing top-level documentation comment for module FooBar"
Style/Documentation:
  Enabled: false

# I want to bulk change in some migrations
Rails/BulkChangeTable:
  Enabled: false

# Ignore annoying warnings from vscode's rubocop plugin
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/BlockComments:
  Enabled: false
